### ISSUE TITLE
about returning custom messages

### ISSUE THREAD

**Issue by q2wdqea** [cloudwego/thrift-gen-validator#16]
I want to return custom message content when defining idl, business needs, look at the following pictures

![image](https://user-images.githubusercontent.com/8363919/216878522-a611f8f9-7a19-4d37-87d3-42d502003484.png)

**Comment by HeyJavaBean** [comment]
You can assert the validator error type and wrap your own biz error.

**Comment by philchia** [comment]
validator error should be a concrete type, including  full path of the field and the error message
